apiVersion: v1
kind: Namespace
metadata:
  name: zenc-production
  labels:
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: zenc-monitoring
  labels:
    environment: production
    type: observability
